# Generated by Django 5.1.2 on 2025-01-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitMakers', '0004_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fitmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitMakers.fitmaker')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('Add', 'Add'), ('Use', 'Use')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.toolsinventory')),
            ],
        ),
    ]
