# Generated by Django 5.1.2 on 2025-01-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0004_alter_service_description'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Tool', 'Tool'), ('Fabric', 'Fabric')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('fitmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitMakers.fitmaker')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('Add', 'Add'), ('Use', 'Use')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
    ]
