# Generated by Django 5.1.2 on 2025-01-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_material_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
