# Generated by Django 5.1.2 on 2025-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem_fabric_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='purchase_price_per_unit',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='sell_price_per_unit',
            new_name='purchase_price',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Fabric', 'Fabric'), ('Dress', 'Dress')], max_length=50),
        ),
    ]
