# Generated by Django 5.1.2 on 2025-01-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitFinders', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressmeasurement',
            name='fit_finder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitFinders.fitfinder'),
        ),
    ]
