# Generated by Django 5.1.2 on 2025-01-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitFinders', '0001_initial'),
        ('measurements', '0002_dressmeasurement_fit_finder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressmeasurement',
            name='fit_finder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitFinders.fitfinder'),
        ),
    ]
