# Generated by Django 5.1.2 on 2025-02-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_dresstype_sell_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressmeasurement',
            name='chest_or_hip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dressmeasurement',
            name='dress_long',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
