# Generated by Django 5.1.2 on 2025-01-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FitMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('shop_started', models.DateField(blank=True, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=11, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, to='fitMakers.services')),
            ],
        ),
    ]
