# Generated by Django 5.1.2 on 2025-01-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
