# Generated by Django 5.1.2 on 2025-01-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
