# Generated by Django 5.1.2 on 2025-01-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0003_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
