# Generated by Django 5.1.2 on 2025-01-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0005_fitmaker_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitmaker',
            name='fabric_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
