# Generated by Django 5.1.2 on 2025-01-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0006_fitmaker_fabric_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
