# Generated by Django 5.1.2 on 2025-01-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0007_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
