# Generated by Django 5.1.2 on 2025-01-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0009_category_dress_dressrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='image_url',
            new_name='image',
        ),
    ]
