# Generated by Django 5.1.2 on 2025-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitMakers', '0010_rename_image_url_dress_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dress',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
