# Generated by Django 5.1.2 on 2025-01-08 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitFinders', '0001_initial'),
        ('fitMakers', '0006_fitmaker_fabric_profit'),
        ('inventory', '0006_inventoryitem_sell_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fabric_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dress_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('dress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dress_orders', to='inventory.inventoryitem')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_orders', to='inventory.inventoryitem')),
                ('fit_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitFinders.fitfinder')),
                ('fit_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitMakers.fitmaker')),
            ],
        ),
    ]
