# Generated by Django 5.1.2 on 2025-01-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_purchase_price_per_unit_inventoryitem_discount_price_and_more'),
        ('measurements', '0004_dresstype_sell_price_per_unit'),
        ('orders', '0004_neworder_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dress_price',
            new_name='fabric_OR_dress_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fabric_price',
            new_name='tailorService_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric',
        ),
        migrations.AddField(
            model_name='order',
            name='fabric_OR_dress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='fabric_OR_dress_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='tailorService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.dresstype'),
        ),
        migrations.DeleteModel(
            name='NewOrder',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
