# Generated by Django 5.1.2 on 2025-02-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitFinders', '0001_initial'),
        ('fitMakers', '0011_dress_is_featured_dress_is_upcoming'),
        ('inventory', '0010_rename_purchase_price_per_unit_inventoryitem_discount_price_and_more'),
        ('measurements', '0005_alter_dressmeasurement_chest_or_hip_and_more'),
        ('orders', '0005_remove_orderitem_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_or_dress_quantity', models.PositiveIntegerField(default=1)),
                ('purchased', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_or_dress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('fit_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitFinders.fitfinder')),
                ('fit_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitMakers.fitmaker')),
                ('tailorService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.dresstype')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
