# Generated by Django 5.1.2 on 2025-02-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={},
        ),
    ]
