# Generated by Django 5.1.2 on 2025-02-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cartlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={'ordering': ['added_at']},
        ),
    ]
