# Generated by Django 5.1.2 on 2025-02-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cartlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='cartlist',
            name='updated_at',
        ),
    ]
